#!/bin/sh

dir="$(pwd)"

# Update passwords
cd ../env
git pull

# Copy .env
cp .env $dir
cd $dir

export $(cat .env | grep -v ^# | xargs)

# Replace config.json env
perl -pi.bak -e 's/\$(\{)?([a-zA-Z_]\w*)(?(1)\})/$ENV{$2}/g' homebridge/config/config.json

docker-compose up -d
